const roomTemplates = [
  { filename: 'front.png', doors: { north: true, south: false, east: false, west: false }},
  { filename: 'hall.png', doors: { north: true, south: true, east: true, west: true } },
  { filename: 'Elegant Isometric Room with Chandelier.png', doors: { north: true, south: true, east: true, west: false }, flipped:true },
  { filename: 'Astronomy Observatory in Pixel Art.png', doors: { north: true, south: true, east: true, west: false } },
    { filename: 'bathroom.png', doors: { north: true, south: false, east: false, west: false } },
    { filename: 'Boiler Room in Pixel Art.png', doors: { north: true, south: false, east: true, west: false } },
    { filename: 'furnace.png', doors: { north: false, south: true, east: true, west: false } },
    { filename: "Children's Bedroom with Toys.png", doors: { north: true, south: false, east: false, west: false } },
    { filename: 'Clock Showcase in Warm Tones.png', doors: { north: true, south: true, east: false, west: false } },
    { filename: 'Cozy Coat Closet in PixelArt.png', doors: { north: true, south: false, east: false, west: false } },
    { filename: 'Cozy Pixel Bedroom with Vintage Flair.png', doors: { north: true, south: false, east: true, west: false } },
    { filename: 'Cozy Room with Framed Landscapes.png', doors: { north: false, south: true, east: true, west: false } },
    { filename: 'Digital Control Room in Pixel Art.png', doors: { north: false, south: true, east: true, west: false } },
    { filename: 'Dollhouse Room with Wooden Table.png', doors: { north: true, south: true, east: true, west: false } },
    { filename: 'Elegant Chairs by Open Doorway.png', doors: { north: true, south: true, east: false, west: false } },
    { filename: 'Empty Retro Room with Dark Doorway.png', doors: { north: true, south: true, east: false, west: false } },
    { filename: 'Empty Retro Room with Dark Doorway.png', doors: { north: false, south: false, east: true, west: true }, flipped:true },
    { filename: 'Empty Room with Herringbone Floor.png', doors: { north: false, south: true, east: true, west: false } },
    { filename: 'Isometric Office with Fax and Cooler.png', doors: { north: true, south: false, east: true, west: true } },
    { filename: 'Isometric Pixel Art Dining Room.png', doors: { north: false, south: true, east: false, west: true } },
    { filename: 'Isometric Room with Aquariums.png', doors: { north: true, south: false, east: true, west: false } },
    { filename: 'Isometric Room with Red Carpet.png', doors: { north: true, south: true, east: false, west: false } },
    { filename: 'Isometric Room with Security Cameras.png', doors: { north: false, south: false, east: false, west: true } },
    { filename: 'Pixel Art Bathroom Setup.png', doors: { north: false, south: false, east: false, west: true } },
    { filename: 'Pixel Art Church Interior.png', doors: { north: true, south: false, east: true, west: false } },
    { filename: 'Pixel Art Cozy Library Interior.png', doors: { north: true, south: true, east: false, west: false } },
    { filename: 'Pixel Art Cozy Library Scene.png', doors: { north: true, south: false, east: false, west: true } },
    { filename: 'Pixel Art Cozy Room with Benches.png', doors: { north: true, south: true, east: false, west: false } },
    { filename: 'Pixel Art Cozy Room with Benches.png', doors: { north: false, south: false, east: true, west: true }, flipped:true },
    { filename: 'Pixel Art Crown on Pedestal.png', doors: { north: true, south: true, east: false, west: true } },
    { filename: 'Pixel Art Empty Room with Mirrors.png', doors: { north: false, south: true, east: true, west: false } },
    { filename: 'Pixel Art Gallery with Statues and Paintings.png', doors: { north: false, south: true, east: true, west: false } },
    { filename: 'Pixel Art Gym Room Overview.png', doors: { north: true, south: false, east: true, west: true } },
    { filename: 'Pixel Art Gym Workout Room.png', doors: { north: true, south: true, east: false, west: true } },
    { filename: 'Pixel Art Laboratory with Glassware.png', doors: { north: true, south: true, east: false, west: true } },
    { filename: 'Pixel Art Room Corner with Mirror.png', doors: { north: true, south: true, east: false, west: false } },
    { filename: 'Pixel Art Room with Aquarium.png', doors: { north: true, south: false, east: true, west: false } },
    { filename: 'Pixel Art Workshop Scene.png', doors: { north: true, south: false, east: false, west: false } },
    { filename: 'Pixel Nursery with Celestial Mobile.png', doors: { north: false, south: false, east: false, west: true },flipped:true },
    { filename: 'Pipes and Valves in a Basement.png', doors: { north: true, south: true, east: false, west: false } },
    { filename: 'Pub Corner in Pixel Art.png', doors: { north: false, south: true, east: true, west: false } },
    { filename: 'Retro Indoor Garden in Pixel Art.png', doors: { north: true, south: false, east: false, west: true } },
    { filename: 'Retro Office in Pixel Art.png', doors: { north: true, south: false, east: true, west: true } },
    { filename: 'Retro Pixel Art Living Room.png', doors: { north: true, south: false, east: true, west: false } },
    { filename: 'Retro Pixel Bedroom with Bunk Bed.png', doors: { north: true, south: false, east: false, west: false } },
    { filename: 'Retro Pixel Kitchen Interior.png', doors: { north: true, south: true, east: true, west: false } },
    { filename: 'Retro Room with Aquarium and Desk.png', doors: { north: false, south: false, east: false, west: true }, flipped:true },
    { filename: 'Royal Throne Room in Pixels.png', doors: { north: true, south: true, east: false, west: true } },
    { filename: 'Security Monitoring Room in Pixel Art.png', doors: { north: true, south: false, east: false, west: true } },
    { filename: 'Sunroom with Lush Greenery.png', doors: { north: false, south: true, east: true, west: false } },
    { filename: 'Symmetrical Room with Ornate Benches.png', doors: { north: false, south: false, east: true, west: true } },
    { filename: 'bathroom.png', doors: { north: true, south: false, east: false, west: false } },
    { filename: 'closet.png', doors: { north: false, south: false, east: false, west: true }, flipped:true },
    { filename: 'kitchen.png', doors: { north: true, south: true, east: false, west: false } }
  ];